---
# GitHub Actions Workflow CI/CD
#

on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout our code
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Run node tests
        run: |
          cd serverside
          node testAllQuotes.js

  build:
    name: build
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout our code
        uses: actions/checkout@v2
      - run: |
          ls
          echo "build stage"

  deploy:
    name: deploy
    needs: [test, build]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      -  run: echo "deploy stage"
