---
# GitHub Actions Workflow CI/CD
#

on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout our code
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Run node tests
        working-directory: ./app/serverside
        run: node testAllQuotes.js

  build:
    name: build
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout our code
        uses: actions/checkout@v2
      - run: |
          ls
          echo "build stage"

  system:
    name: system
    needs: [test, build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout our code
        uses: actions/checkout@v2    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Setup InSpec
        run: curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P inspec
      - name: Create Terraform VM
        working-directory: ./terraform
        run: |
          cd test
          terraform init
          terraform plan
          terraform output --json >  ../verify/files/terraform.json
          sed -i '1d' ../verify/files/terraform.json
          sed -i '8,$d' ../verify/files/terraform.json
      - name: Run InSpec tests
        working-directory: ./terraform
        env: 
          CHEF_LICENSE: accept-no-persist
        run: |
          inspec exec verify
      # - name: Create Terraform VM
      #   working-directory: ./terraform
      #   run: |
      #     cd test
      #     terraform init
      #     terraform plan
      #     ls
      #     pwd
      #     terraform output --json >  ../terraform.json
      #     sed -i '1d' ../terraform.json
      #     sed -i '8,$d' ../terraform.json
      #     cat ../terraform.json | jq .instance_ip_addr.value | tr -d \"
      # - name: Run InSpec tests
      #   working-directory: ./terraform
      #   env: 
      #     CHEF_LICENSE: accept-no-persist
      #   run: |
      #     cd test
      #     cat ../terraform.json | jq .instance_ip_addr.value | tr -d \"
      #     export AWS_IP=$(cat ../terraform.json | jq .instance_ip_addr.value | tr -d \")
      #     ls
      #     echo "AWS IP: $AWS_IP"
      #     inspec exec ../verify
  deploy:
    name: deploy
    needs: [test, build]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
      -  run: echo "deploy stage"
